# Generated by Django 3.1.1 on 2021-09-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
